/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#c8e6ff",
        "tertiary-fixed-dim": "#a3cbea",
        "primary-container": "#991b1b",
        "inverse-on-surface": "#ffedeb",
        "inverse-surface": "#392e2d",
        "primary-fixed-dim": "#fca5a5",
        "on-primary-fixed-variant": "#b91c1c",
        "on-secondary-fixed": "#001b3d",
        "outline": "#897170",
        "surface-container-highest": "#f2dedd",
        "background": "#fff8f7",
        "primary": "#dc2626",
        "on-primary": "#ffffff",
        "on-background": "#231919",
        "surface-container-low": "#fff0ef",
        "secondary": "#465f88",
        "tertiary-container": "#00344d",
        "on-tertiary-fixed": "#001e2f",
        "surface-tint": "#ef4444",
        "on-tertiary-fixed-variant": "#204b65",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "secondary-container": "#b6d0ff",
        "surface-container-high": "#f8e4e2",
        "surface-dim": "#e9d6d4",
        "surface-variant": "#f2dedd",
        "on-tertiary": "#ffffff",
        "outline-variant": "#dcc0bf",
        "on-surface-variant": "#564241",
        "secondary-fixed": "#d6e3ff",
        "error-container": "#ffdad6",
        "on-tertiary-container": "#759dba",
        "primary-fixed": "#fef2f2",
        "surface": "#fff8f7",
        "secondary-fixed-dim": "#aec7f7",
        "surface-container": "#fde9e8",
        "on-secondary-fixed-variant": "#2e476f",
        "on-error-container": "#93000a",
        "on-secondary-container": "#3f5881",
        "on-primary-fixed": "#dc2626",
        "on-surface": "#231919",
        "tertiary": "#001e2f",
        "error": "#ba1a1a",
        "inverse-primary": "#fca5a5",
        "on-secondary": "#ffffff",
        "on-primary-container": "#fecaca",
        "surface-bright": "#fff8f7"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "container-margin": "16px",
        "base": "8px",
        "gutter": "16px",
        "lg": "24px",
        "xs": "4px",
        "md": "16px",
        "sm": "8px",
        "xl": "32px"
      },
      fontFamily: {
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "display-md": ["Inter"],
        "display-lg": ["Inter"],
        "label-sm": ["Inter"],
        "label-md": ["Inter"],
        "headline-sm": ["Inter"]
      },
      fontSize: {
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "display-md": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "display-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "label-sm": ["11px", {"lineHeight": "14px", "fontWeight": "600"}],
        "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.01em", "fontWeight": "500"}],
        "headline-sm": ["20px", {"lineHeight": "28px", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
